In [ ]:
!pip install -q transformers

In [ ]:
import re
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_recall_fscore_support, accuracy_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, set_seed

from google.colab import files
files.upload()

Saving english_training_final.csv to english_training_final (3).csv
Saving mongolian_expanded_FINAL.csv to mongolian_expanded_FINAL (3).csv

{'english_training_final (3).csv': b'\xef\xbb\xbftext,label,source\nWe just announced that the first participants in each age cohort have been dosed in the Phase 2 study of our mRNA vaccine (mRNA-1273) against novel coronavirus. Read more: https://t.co/woPlKz1bZC #mRNA https://t.co/9VGUoJu5cS,0,Constraint\nWe just announced that we have shipped vials of mRNA-1273 the Company\xe2\x80\x99s vaccine against the novel coronavirus to the NIH to be used in the planned Phase 1 study in the U.S. https://t.co/jNarQEkGhr https://t.co/o7EoaYeQH1,0,Constraint\nWe are delighted that 78 high- and upper-middle countries and economies have now confirmed they will participate in the COVAX Facility and the number is growing. I urge those who have not yet joined to do so by the 18th of September-@DrTedros #COVID19,0,Constraint\nCDC Recommends Mothers Stop Breastfeeding To Boost Vaccine Efficacy,1,Constraint\nScientists at AstraZeneca complain their work on a coronavirus vaccine keeps being delayed by Noddy Holder ringing up to ask if it will be ready by Christmas https://t.co/2lmYzTnAPx,1,Constraint\n"An article claiming that ""Bill Gates\' vaccine"" would modify human DNA.",1,Constraint\nSeasonal influenza vaccination will be mandatory in Georgia this fall. COVID-19 mortality rates are significantly lower than the fatalities caused by other viruses.,1,Constraint\n@WHO Solidarity Trials are also underway in many countries. Once these projects are complete controlling #COVID19 effectively will be easier due to the availability of proper medicines vaccines etc. as did to control various infectious diseases across the world.,0,Constraint\nAs of today there are 23917 active #COVID19 cases in #Mumbai District #Maharastra: https://t.co/6CcqIYgbXL @MoHFW_INDIA @drharshvardhan @DrHVoffice @MantralayaRoom #COVID__19 #Covid_19 #COVID\xe3\x83\xbc19 #CoronaUpdatesInIndia #Coronavirus #CoronaVirusUpdates #CoronavirusPandemic https://t.co/k6ICon5kZ6,0,Constraint\nThis is an image of a suspected coronavirus vaccine causing COVID-19.,1,Constraint\nBill Gates profits from vaccination and wants to reduce the world\'s population.,1,Constraint\nNasal flu vaccine side effects do not cause covid,1,Constraint\n_Photo of a vaccine developed by U.S. scientists for COVID-19._,1,Constraint\n@drharshvardhan dispels doubts raised over failure of one vaccine in clinical trials says trials are continuing only after expert committee reappraisal. \xe2\x80\x9cNo significant mutation in SARS-CoV-2 in India\xe2\x80\x9d. \xe2\x80\x9cICMR is actively exploring saliva-based test for COVID-19\xe2\x80\x9d. @PIB_India,0,Constraint\nScientists are expressing cautious optimism that a COVID-19 vaccine can be ready to go by the late spring of 2021 although it\xe2\x80\x99s unclear how much longer it would take to distribute the vaccine widely. https://t.co/srNfKUra8c,1,Constraint\n"It\'s possible that some vaccine could be available at the end of the year. CSA Patrick Vallance says a vaccine could be available in ""small amounts for certain groups"" adding that we\'re \'more likely to see vaccines over the first half of next year.\' https://t.co/N2tOTQ6zuh https://t.co/PZLzrn3EGo",0,Constraint\nIn phase 1 doses will be allocated proportionally to all participating countries simultaneously to reduce overall risk. In phase 2 consideration will be given to countries\xe2\x80\x99 in relation to threat and vulnerability-@DrTedros #COVID19 https://t.co/1KOCC24gcX,0,Constraint\n"Great news! #Carona virus vaccine ready. Able to cure patient within 3 hours after injection. Hats off to US Scientists.\n\nRight now Trump announced that Roche Medical Company will launch the \nvaccine next Sunday, and millions of doses are ready from it !!! Note : \nThis message requires confirmation",1,Constraint\nA DNA vaccine* has been shown to work in rhesus monkeys; after exposing the vaccinated monkeys to COVID they had less virus in their lungs. Read the study from @ScienceMagazine --&gt; https://t.co/lr8f3qmP5v,0,Constraint\nNEWS! Anti-vaxxers close to deciding which medical conditions they will pretend are caused by Coronavirus vaccine https://t.co/daWxNYpj86 https://t.co/eNvXR50ByR,1,Constraint\n"Prime Minister Boris Johnson says the government will ""very shortly"" be setting out ""the priority of the groups that we think should have COVID tests"". Follow live updates as the PM faces questions from the liaison committee: https://t.co/MCYJ946KfV https://t.co/qlPstqmj0g",0,Constraint\n"@DrJudyAMikovits What promises that a viable vaccine can be developed for COVID-19 virus. So, i think they should rehire Judith Mikovits who is a living scientific encyclopedia on viral research. She was involved with the scientific research that permitted",1,Constraint\n"Covid-19 vaccine by Oxford university a success, 72 people \'cured\'",1,Constraint\n"Young people ""have a greater chance of being killed by the HPV vaccine than COVID-19.\xe2\x80\x9d",1,Constraint\n"Amoxi"" Capsule made in US is the only medicine that can completely cure COVID-19.\nEgyptian Health Minister arrive in Italy with secret coronavirus cure.\n Dr Charles Lieber a Harvard professor has been arrested in the USA for manufacturing the coronavirus and selling it to China. A video news report from WCVB a TV station in Boston Massachusetts is shared with the Facebook post.\nMountain Matterhorn in Switzerland was lit in three colours of Indian flag as a token of gratitude to India for sending Hydroxychloroquine.\nAl-Azhar Imam said he is considering exceptions on Ramadan fasting as the research says that the mouth must be kept wet to prevent COVID-19\n Japanese Nobel Tasuku Honjo says coronavirus was created in the Wuhan laboratory\nA man collapses in 5 minutes after showing COVID-19 symptoms in India.\nCelebrities spreading misinformation about coronavirus and the Janata curfew in India.\n Multiple posts shared repeatedly on Facebook and Twitter since March 2020 claim that Israel has reported zero deaths from the novel coronavirus which causes the disease COVID-19. The posts also claim Israeli citizens have protected themselves from COVID-19 by drinking a remedy of hot water lemon and baking soda which purportedly \xe2\x80\x9ckills\xe2\x80\x9d the virus.\n CDC suddenly lost 30000 deaths from coronavirus from its data thus proving the virus is not as serious as it seems.\nPhotos of coronavirus patients being treated on the road in Italy.\nIndian actor Shah Rukh Khan donated money to Pakistan to fight coronavirus and did not help India at all.\nRussian President Vladimir Putin has ordered Russia\xe2\x80\x99s population to stay at home for 15 days or face five years in jail.\nIndian Army has set-up a 1000 bed quarantine facility in Rajasthan\'s Barmer.\nLeonardo Da Vinci Hospital a COVID-19 reference hospital in Fortaleza Brazil is empty. A video ""proves"" there was no one at the areas open to the public.\n President Trump\'s claim that he inherited no ventilators from the Obama administration.\nAn audio where an unidentified person links the virus that causes COVID-19 with the massive flu vaccination campaign.\nBlack body bags being referred to as deaths in New York and the reason a lockdown is essential.\nMustard oil prevents a person from getting infected with COVID-19.\nNorth Carolina\xe2\x80\x99s health department is ""telling hospitals that if they decide to do elective surgeries they won\xe2\x80\x99t be eligible to receive (protective equipment) from the state.\xe2\x80\x9d\n After coronavirus pandemic Chinese president said it\'s China\'s time to lead the world.\nThe nurses that Boris Johnson claimed saved his life are not registered in the UK.\nA claim that India\xe2\x80\x99s Ministry of Home Affairs has made it a \xe2\x80\x9cpunishable offense\xe2\x80\x9d for citizens to publish posts on social media about the novel coronavirus has been shared repeatedly on Facebook Twitter and WhatsApp.\n Says Nancy Pelosi was \xe2\x80\x9ccaught trying to include abortion funding in bill to combat coronavirus.\xe2\x80\x9d\nA video of a man rebuking foreigners has been viewed thousands of times on social media alongside a claim that the Guinean government has ordered the arrest of all Chinese nationals in the country while awaiting the safe return of Guineans from China.\n The U.S. is the only country on earth that is protesting being locked down.\nPhoto of Kurnool MLA (Hafeez Khan) making a nurse to touch the feet of a religious head in Viswabharathi Medical College who had to come to the COVID-19 quarantine facility.\nNew York State Governor shows data that proves that isolation is ineffective against COVID-19.\nHomeopathic product Oscillococcinum protects against COVID-19.\nCDC admitted to lying about COVID-19 death stats.\nNotice for preparing emergency drugs was released on social media for alumni of Seoul National University College of Medicine.\nBelgian doctors turn their back on WHO director.\nDr. Li Wenliang (the Chinese whistleblower doctor) has proposed that drinking tea can cure COVID-19.\nAny person arrested for violating lockdown in the night will not get bail until the lockdown is over in the state of Gujarat in India.\n US President Donald Trump tested positive for COVID-19.\nA picture with a quote from doctor Vincenzo Puro who allegedly said that asymptomatic people cannot infect others that the virus is not lethal and that the pandemic is a ""hoax"".\n Prince Charles recovered from COVID-19 with the help of Ayurvedic treatment.\n A video shows a Superintendent of police announcing the extension of Lokckdown in Maharashtra India till May 30.\n A WhatsApp audio claims that the Infanta Sof\xc3\xada Hospital in Madrid has 15 children in serious condition due to COVID-19 and that there are three other children in the Talavera de la Reina Hospital.\nVideo shows coronavirus patients and doctors.\nA video claims to show that the Nigerian government has spent US$2 million to ""import"" Chinese doctors and supplies.\nRiots in London due to the unavailability of food items. The United Kingdom will be locked down by tonight. Army soldiers take to the UK streets.\nA set of claims passed as instructions to be followed during the COVID-19 pandemic period.\n Facebook post claims that the Latvian app Apturi Covid (Stop Covid) which was created to warn people who have been close to an infected person will be used so the government can track all the people from the contact list and record their locations.\nAaj Tak channel aired a program that said drinking alcohol or smoking weed can cure COVID-19.\n President Donald Trump tweeted \xe2\x80\x9cCoronavirus vaccine from Israel! Stock market up! Economy even stronger now! Besides US Israel best at inventions: Judaism olives. Wonderful vaccine will stop Corona DEAD around world. Can\xe2\x80\x99t make vaccines when being bombed not have been possible without peace I created in Israel!\xe2\x80\x9d\nItaly official Giulio Gallera: China lies to us. The date China provided is false. Italy has become Wuhan and the medical system has a breakdown.\nJo\xc3\xa3o Doria governor of S\xc3\xa3o Paulo forbade doctors to give chloroquine to COVID-19 patients.\nA blog post has been shared thousands of times in multiple Facebook posts which claim it shows a video of a baby who died after being infected with the novel coronavirus which causes the disease COVID-19.\n A vaccine for coronavirus was available since 2001.\n Video showing policemen picking banknotes with sticks linking it with coronavirus.\nWe can\'t make a vaccine that works for flu no vaccine for the respiratory syncytial virus (RSV) and we can\'t cure cancer. Yet somehow scientists can make a vaccine for COVID-19 in six months?\nMumbai and Pune is going under military lockdown\nWhat we need to do to defeat the coronavirus is to consume more alkaline foods above the virus\xe2\x80\x99 pH level.\nIndian Actor Aamir Khan gives Rs. 15000 to poor people in 1Kg wheat flour.\n The photo shows the funeral of Turkish deceased general Aytac Yalman due to COVID-19.\nThe coronavirus responsible for COVID-19 is a mix of SARS and HIV.\nTwo doctors in Bakersfield California said at a press conference that isolation measures affect the immune system and that unrestrictive controls in countries like Sweden have worked.\n Article says that the Vatican confirmed that the Pope and two assistants have coronavirus.\nHerbal tea made of malunggay and kamias leaves is a cure for COVID-19 the disease caused by the novel coronavirus.\nA video of police officers immobilizing a screaming woman. The caption states that they were being beaten by the police because they refuse to go to their houses during lockdown in Minas Gerais Brazil\n Cuba\'s low number of COVID-19 deaths is due to its use of hydroxychloroquine to treat patients\nA video of the doctor linked to the anti-vaccine movement Chinda Brandolino on the origin of COVID-19.\n There is a confirmed case of coronavirus in a Bogot\xc3\xa1 hospital.\nA video showing migrant laborers from Surat city in India are being sent back to Surat after their home states refused to take them back at the state border.\nOhio Gov. Mike DeWine released 4300 prisoners and is now warning residents of a possible crime wave.\n It\'s not a virus but 5G that is causing disease and deaths\nAn arrest by the Federal Bureau of Investigation (FBI) of a professor who had ties to China is connected to the coronavirus pandemic.\nA photo of a list of purported symptoms and treatments for the novel coronavirus which causes the disease COVID-19 has been shared hundreds of times in multiple posts on Facebook Twitter and Instagram. The purported remedies include a daily dose of vitamins; exposure to sunlight; and a diet of alkaline foods.\n Police catches coronavirus positive patient on the road.\n In the 30-second viral video a man lifts his shirt and challenges aa police officer who is pointing a gun at him. Another police officer kicks the man from behind pins him down on the road and makes an arrest. The text overlaid on the video reads ""Italy says lockdown they mean it.",1,Constraint\nIn this video italian representative Sara Cunial tells the truth about Bill Gates and its will to control world population through vaccines and medical experiment.,1,Constraint\nAt the same time bilateral vaccine deals and vaccine nationalism could compromise equitable access and hold up progress for all countries in bringing the #COVID19 pandemic to an end-@DrTedros,0,Constraint\n"@jsolomonReports Soon 67\nNever had flu vaccine, never had flu\nMost all I know who got flu vaccine also got flu\nThat\xe2\x80\x99s 1st person knowledge, not conjecture\n\nAlt: Organic dk greens, protein, exercise, H2O, sodium bicarbonate, D3, C, iodine, etc\n\nJESUS is my physician\nGreatest ever was, is, will be",1,Constraint\nRT @DrTedros: COVAX is a groundbreaking way to pool R&amp;D &amp; procurement risks across multiple vaccines. It enables countries to place collect\xe2\x80\xa6,0,Constraint\n_A vaccine for COVID-19 has been found._,1,Constraint\n"Medical director at PHE Dr Yvonne Doyle says having both #COVID19 and the flu is a ""very risky situation"" as she encourages people who are invited for a flu vaccine to have it. #KayBurley Live updates: https://t.co/I0Ya5YFTvZ https://t.co/Qs5l3S0YFE",0,Constraint\n"Trump announced that Roche Medical Company will launch the vaccine next Sunday, and millions of doses are ready from it !!!",1,Constraint\n@HSELive You should also high-dose with Vitamin D. Extensive clinical evidence that sufficient Vitamin D reduces severity of Covid-19. Hospital protocol for Covid-19 in France to immediately test for and treat Vit D deficiency. Chronic Vit D deficiency in Ireland \xe2\x80\x93 why no public campaign?,1,Constraint\nThe governor of Sao Paulo contracted COVID-19 after being vaccinated with the Sinovac Biotech vaccine.,1,Constraint\nWhen will a Covid-19 vaccine be available to the public? No one\'s sure yet but the target is sometime in early 2021. https://t.co/uwEPWev9HO,0,Constraint\nAs the #coronavirus clings on reasserting itself in countries like the UK and US the hopes and fears of politicians scientists and the rest of humanity centre on a relatively small number of vaccines currently in development https://t.co/8S2nyDR04o,0,Constraint\n#FACTCHECK : @WHO has repeatedly said that a vaccine of #COVID2019 is not yet available. Yet #FakeNews keeps emerging. Here is #Factchecking one more such claim https://t.co/ozvV92FE8s,1,Constraint\nThe first test results for the Moderna vaccine are disappointing.,1,Constraint\nBharat Biotech\xe2\x80\x99s Vice President Did Not Under Go Clinical Trial For His Company\xe2\x80\x99s #COVID19 Vaccine \xe2\x80\x98Covaxin\xe2\x80\x99. An Image with false claim doing the rounds on social media. #covaxine #COVID\xe3\x83\xbc19 #FactCheck https://t.co/pQWzblPEuV,1,Constraint\nNew York schools add a COVID-19 vaccine to the mandatory school schedule.,1,Constraint\nA Pentagon study found that people who get the flu vaccine are 36% more likely to get COVID-19.,1,Constraint\nPlease share this video Neem leaves powder can cure corona within hours please share this video allah had blessed us with the corona vaccine #coronavirus #coronavacccine @WorldHealthOrg2,1,Constraint\nClaim: Top Georgian health official Gamkrelidze said the COVID-19 vaccine will be available in Georgia in several weeks,1,Constraint\nClaim that supermarket workers are required to have a flu vaccination or face dismissal.,1,Constraint\nOur partner the @CEPIvaccines is supporting 9 candidate #COVID19 vaccines that will be made available to the COVAX facility if successful 7 of which are in clinical trials. We\xe2\x80\x99re also in discussions about 4 other promising vaccines-@DrTedros,0,Constraint\nWe have completed enrollment of our Phase 2 study of mRNA-1273 our vaccine candidate against COVID-19. Read this morning\'s press release here: https://t.co/RZWlyCgUUd https://t.co/FBMsaH20Pg,0,Constraint\n_Israel has found a cure and a vaccine for coronavirus._,1,Constraint\nA @WebMD Poll: 27.3% of readers would get a #coronavirus vaccine as soon as it\xe2\x80\x99s available; more than half would in the first year. https://t.co/uJHegnjq0X,0,Constraint\n"BREAKING: Nicola Sturgeon has urged Boris Johnson to call a Cobra meeting over rising #coronavirus infections. She said: ""Given serious situation across UK I have also asked again that a 4 nations COBR meeting takes place over next 48 hours."" More: https://t.co/M9zqxeP5Ur https://t.co/roHnxgCT82",0,Constraint\nRT @DDIndialive: India\'s first #COVID19 vaccine candidate COVAXIN\xe2\x84\xa2 gets approval for human trials; it has been jointly developed by @ICMR\xe2\x80\xa6,0,Constraint\n#COVID vaccine target in the US moves back to mid-2021; requires a full FDA approval process. https://t.co/Cnrn37a3nl,0,Constraint\nThe novel coronavirus was made in a lab and is now spread as a way to force vaccinate people.,1,Constraint\nUPDATE: #COVID19 #CoronaVirus in Italy: \xe2\x9e\xa1\xef\xb8\x8fReproduction number R &lt;1 \xe2\x9e\xa1\xef\xb8\x8fNo herd immunity reached \xe2\x9e\xa1\xef\xb8\x8f20% return to pre-lockdown mobility may lead to resurgence in deaths \xe2\x9e\xa1\xef\xb8\x8fEnhanced surveillance needed to reduce risk of resurgence \xf0\x9f\x94\xb0Report https://t.co/lcFch0FxCt https://t.co/pnN4MdIEaY,0,Constraint\nEquitable global access to tests treatments and vaccines is key to ending #COVID19 fairly effectively and efficiently. Because if one of us is at risk we are all at risk. We are only safe when everybody is safe. https://t.co/rihWnivQ0V,0,Constraint\n"I am also doing this, taking Vitamin D for COVID.\n\nI think the evidence is moderate-ish right now, not conclusive. But there\'s no real downside at all to taking moderate doses AFAIK. And people living in the northern latitudes in the winter probably need Vitamin D anyways. https://t.co/aVSGw6LPhn",1,Constraint\nFor example once a successful vaccine has been identified WHO\xe2\x

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
covid_words = ["covid", "coronavirus", "sars-cov-2", "corona virus", "pandemic"]

def clean(t):
    t = re.sub(r"http\S+|www\.\S+", " ", str(t))
    t = re.sub(r"<[^>]+>", " ", t)
    return re.sub(r"\s+", " ", t).strip()

def load(path):
    df = pd.read_csv(path)
    df["text"] = df["text"].apply(clean)
    df = df[df["text"].str.len() > 0].drop_duplicates("text").reset_index(drop=True)
    df["label"] = df["label"].astype(int)
    return df

def has_covid(t):
    t = t.lower()
    return any(w in t for w in covid_words)

english = load("english_training_final.csv")
mongolian = load("mongolian_expanded_FINAL.csv")
print("English:", len(english), " Mongolian:", len(mongolian))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

English: 1111  Mongolian: 495

In [ ]:
class Claims(torch.utils.data.Dataset):
    def __init__(self, texts, labels):
        self.enc = tokenizer(list(texts), truncation=True, padding="max_length", max_length=128)
        self.labels = list(labels)
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, i):
        item = {k: torch.tensor(v[i]) for k, v in self.enc.items()}
        item["labels"] = torch.tensor(int(self.labels[i]))
        return item

def train(train_df, seed, start_from="xlm-roberta-base"):
    set_seed(seed)
    model = AutoModelForSequenceClassification.from_pretrained(start_from, num_labels=2)
    args = TrainingArguments(output_dir="tmp", num_train_epochs=4,
                             per_device_train_batch_size=16, per_device_eval_batch_size=32,
                             learning_rate=2e-5, logging_steps=50, save_strategy="no",
                             seed=seed, report_to=[])
    trainer = Trainer(model=model, args=args, train_dataset=Claims(train_df["text"], train_df["label"]))
    trainer.train()
    return model

def score(model, test_df):
    model.eval()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    ds = Claims(test_df["text"], test_df["label"])
    loader = torch.utils.data.DataLoader(ds, batch_size=32)
    preds, gold = [], []
    with torch.no_grad():
        for batch in loader:
            y = batch.pop("labels")
            batch = {k: v.to(device) for k, v in batch.items()}
            preds += model(**batch).logits.argmax(-1).cpu().tolist()
            gold += y.tolist()
    macro = f1_score(gold, preds, average="macro")
    p, r, f, _ = precision_recall_fscore_support(gold, preds, labels=[0, 1], zero_division=0)
    print("  macro-F1: %.4f | accuracy: %.4f" % (macro, accuracy_score(gold, preds)))
    print("  misinfo recall: %.4f | reliable recall: %.4f" % (r[1], r[0]))
    print("  confusion:", confusion_matrix(gold, preds, labels=[0, 1]).tolist())
    return macro

In [ ]:
en_train, en_test = train_test_split(english, test_size=0.20, stratify=english["label"], random_state=42)
mn_pool, mn_test = train_test_split(mongolian, test_size=0.40, stratify=mongolian["label"], random_state=42)
print("EN train/test:", len(en_train), len(en_test), " MN pool/test:", len(mn_pool), len(mn_test))

en_model = train(en_train, 42)

print("\nEnglish ceiling:")
ceiling = score(en_model, en_test)

print("\nRQ1 zero-shot Mongolian:")
zero_shot = score(en_model, mn_test)

en_model.save_pretrained("en_model")

EN train/test: 888 223  MN pool/test: 297 198

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

English ceiling:
  macro-F1: 0.8647 | accuracy: 0.8655
  misinfo recall: 0.8898 | reliable recall: 0.8381
  confusion: [[88, 17], [13, 105]]

RQ1 zero-shot Mongolian:
  macro-F1: 0.4254 | accuracy: 0.4697
  misinfo recall: 0.7475 | reliable recall: 0.1919
  confusion: [[19, 80], [25, 74]]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
import gc

seeds = [42, 123, 2024]
sizes = [0, 20, 40, 80, 100]
sweep = {}

for n in sizes:
    runs = []
    for seed in seeds:
        if n == 0:
            print("\nsize 0, seed %d (zero-shot):" % seed)
            runs.append(score(en_model, mn_test))
        else:
            sub, _ = train_test_split(mn_pool, train_size=n, stratify=mn_pool["label"], random_state=seed)
            m = train(sub, seed, start_from="en_model")
            print("\nsize %d, seed %d:" % (n, seed))
            runs.append(score(m, mn_test))
            del m; gc.collect(); torch.cuda.empty_cache()
    sweep[n] = (np.mean(runs), np.std(runs))

print("\n=== SWEEP (mean over seeds) ===")
print("English ceiling: %.4f" % ceiling)
for n, (mean, std) in sweep.items():
    print("MN %3d -> %.4f ± %.4f" % (n, mean, std))

size 0, seed 42 (zero-shot):
  macro-F1: 0.4254 | accuracy: 0.4697
  misinfo recall: 0.7475 | reliable recall: 0.1919
  confusion: [[19, 80], [25, 74]]

size 0, seed 123 (zero-shot):
  macro-F1: 0.4254 | accuracy: 0.4697
  misinfo recall: 0.7475 | reliable recall: 0.1919
  confusion: [[19, 80], [25, 74]]

size 0, seed 2024 (zero-shot):
  macro-F1: 0.4254 | accuracy: 0.4697
  misinfo recall: 0.7475 | reliable recall: 0.1919
  confusion: [[19, 80], [25, 74]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 20, seed 42:
  macro-F1: 0.6805 | accuracy: 0.6869
  misinfo recall: 0.8283 | reliable recall: 0.5455
  confusion: [[54, 45], [17, 82]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 20, seed 123:
  macro-F1: 0.6439 | accuracy: 0.6515
  misinfo recall: 0.5051 | reliable recall: 0.7980
  confusion: [[79, 20], [49, 50]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 20, seed 2024:
  macro-F1: 0.6912 | accuracy: 0.7020
  misinfo recall: 0.8889 | reliable recall: 0.5152
  confusion: [[51, 48], [11, 88]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 40, seed 42:
  macro-F1: 0.3333 | accuracy: 0.5000
  misinfo recall: 1.0000 | reliable recall: 0.0000
  confusion: [[0, 99], [0, 99]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 40, seed 123:
  macro-F1: 0.5801 | accuracy: 0.6162
  misinfo recall: 0.9091 | reliable recall: 0.3232
  confusion: [[32, 67], [9, 90]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 40, seed 2024:
  macro-F1: 0.8332 | accuracy: 0.8333
  misinfo recall: 0.8081 | reliable recall: 0.8586
  confusion: [[85, 14], [19, 80]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 80, seed 42:
  macro-F1: 0.8565 | accuracy: 0.8586
  misinfo recall: 0.7374 | reliable recall: 0.9798
  confusion: [[97, 2], [26, 73]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 80, seed 123:
  macro-F1: 0.8936 | accuracy: 0.8939
  misinfo recall: 0.8384 | reliable recall: 0.9495
  confusion: [[94, 5], [16, 83]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 80, seed 2024:
  macro-F1: 0.8367 | accuracy: 0.8384
  misinfo recall: 0.7374 | reliable recall: 0.9394
  confusion: [[93, 6], [26, 73]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 100, seed 42:
  macro-F1: 0.9090 | accuracy: 0.9091
  misinfo recall: 0.8788 | reliable recall: 0.9394
  confusion: [[93, 6], [12, 87]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 100, seed 123:
  macro-F1: 0.8930 | accuracy: 0.8939
  misinfo recall: 0.7980 | reliable recall: 0.9899
  confusion: [[98, 1], [20, 79]]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

size 100, seed 2024:
  macro-F1: 0.8061 | accuracy: 0.8081
  misinfo recall: 0.7071 | reliable recall: 0.9091
  confusion: [[90, 9], [29, 70]]

=== SWEEP (mean over seeds) ===
English ceiling: 0.8647
MN   0 -> 0.4254 ± 0.0000
MN  20 -> 0.6719 ± 0.0203
MN  40 -> 0.5822 ± 0.2041
MN  80 -> 0.8623 ± 0.0236
MN 100 -> 0.8694 ± 0.0452

In [ ]:
import gc

constraint = english[english["source"].str.lower() == "constraint"]
pubhealth = english[english["source"].str.lower() == "pubhealth"]
pub_covid = pubhealth[pubhealth["text"].apply(has_covid)]
pub_other = pubhealth[~pubhealth["text"].apply(has_covid)]

en_covid = pd.concat([constraint, pub_covid])[["text", "label"]]
en_other_test = pub_other.reset_index(drop=True)
mn_covid = mongolian[mongolian["is_covid"] == 1][["text", "label"]]
mn_other_test = mongolian[mongolian["is_covid"] == 0].reset_index(drop=True)

train_df = pd.concat([en_covid, mn_covid], ignore_index=True)
print("COVID train:", len(train_df), "| EN-other test:", len(en_other_test), "| MN-other test:", len(mn_other_test))

en_scores, mn_scores = [], []
for seed in [42, 123, 2024]:
    m = train(train_df, seed)
    print("\nseed %d — English non-COVID:" % seed)
    en_scores.append(score(m, en_other_test))
    print("seed %d — Mongolian non-COVID:" % seed)
    mn_scores.append(score(m, mn_other_test))
    del m; gc.collect(); torch.cuda.empty_cache()

print("\n=== RQ4 (mean over seeds) ===")
print("English non-COVID: %.4f ± %.4f" % (np.mean(en_scores), np.std(en_scores)))
print("Mongolian non-COVID: %.4f ± %.4f" % (np.mean(mn_scores), np.std(mn_scores)))

COVID train: 965 | EN-other test: 357 | MN-other test: 284

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

seed 42 — English non-COVID:
  macro-F1: 0.5179 | accuracy: 0.5266
  misinfo recall: 0.9516 | reliable recall: 0.3004
  confusion: [[70, 163], [6, 118]]
seed 42 — Mongolian non-COVID:
  macro-F1: 0.8935 | accuracy: 0.8944
  misinfo recall: 0.9120 | reliable recall: 0.8805
  confusion: [[140, 19], [11, 114]]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

seed 123 — English non-COVID:
  macro-F1: 0.5973 | accuracy: 0.5994
  misinfo recall: 0.9677 | reliable recall: 0.4034
  confusion: [[94, 139], [4, 120]]
seed 123 — Mongolian non-COVID:
  macro-F1: 0.9201 | accuracy: 0.9225
  misinfo recall: 0.8480 | reliable recall: 0.9811
  confusion: [[156, 3], [19, 106]]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

seed 2024 — English non-COVID:
  macro-F1: 0.5440 | accuracy: 0.5462
  misinfo recall: 0.8871 | reliable recall: 0.3648
  confusion: [[85, 148], [14, 110]]
seed 2024 — Mongolian non-COVID:
  macro-F1: 0.8802 | accuracy: 0.8838
  misinfo recall: 0.8080 | reliable recall: 0.9434
  confusion: [[150, 9], [24, 101]]

=== RQ4 (mean over seeds) ===
English non-COVID: 0.5531 ± 0.0330
Mongolian non-COVID: 0.8979 ± 0.0166